# fly.toml app configuration file generated for shopify-main on 2023-09-05T18:08:50+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "shopify-main"
primary_region = "sin"

[build]

[env]
  HOST = "https://shopify-main.fly.dev"
  PORT = "8081"
  SCOPES = "write_products"
  SHOPIFY_API_KEY = "0c004d75b88b64e568ef7886ef202fb6"

[http_service]
  internal_port = 8081
